### ISSUE TITLE
UserPool and UserPoolUser resources not picked up

### ISSUE THREAD

**Issue by TheOneTrueBaal** [iann0036/AWSConsoleRecorder#17]
**Describe the bug**
When creating a userpool using the AWS cognito console, or adding a user to an existing userpool, (AWS::Cognito::UserPool and AWS::Cognito::UserPoolUser), the Recorder plugin indicates "no recorded actions yet" in the cloudformation when recording is stopped.

**Related Language**
CloudFormation

**To Reproduce**
1. Start recording on the plugin
2. Go to the AWS cognito console
3. Click on "Manage Userpools"
4. Click on "Create a user pool"
5. Enter a Pool name and follow either the "Review defaults" or "Step through settings" routes to create a user pool.
(this creates a UserPool resource, which is not reflected when the console recorder is stopped)
6. After the pool was created, click on "Users and groups"
7. Click on "Create user"
8. Complete the Create user form and click on "Create user".
(this creates a UserPoolUser resource, which is not reflected when the console recorder is stopped)

**Expected behavior**
When the console recorder recording is stopped, the dashboard is expected to show a CloudFormation script of the UserPool and UserPoolUser created.  

**Additional context**
This was test on both Chrome and Firefox.

**Comment by TheOneTrueBaal** [comment]
Thanks for fixing this so quickly.  You're a champ

**Comment by iann0036** [comment]
Forgot to comment 😞

This should be fixed and published now (0.3.3+). Thanks soo much for raising and please feel free to raise more as you find them!
