### ISSUE TITLE
CodeDeploy is using the wrong aws cli command codedeploy instead of deploy

### ISSUE THREAD

**Issue by jverhoeks** [iann0036/AWSConsoleRecorder#26]
**Describe the bug**
CodeDeploy is using the wrong aws cli command codedeploy instead of deploy

**Related Mapping**
CodeDeploy

**Related Language**
AWS CLI 
https://docs.aws.amazon.com/cli/latest/reference/deploy/index.html

**To Reproduce**
1. To the aws codedeploy and list deployments
2. In AWS Cli recording tab:  aws codedeploy list-deployments --region eu-west-1

**Expected behavior**
aws deploy list-deployments --region eu-west-1

**Comment by iann0036** [comment]
Hi Jacob,

Thank you very much for your report. I'll have that fixed in the next release, 0.3.10.
