### ISSUE TITLE
AWS config Rules

### ISSUE THREAD

**Issue by schittam** [iann0036/AWSConsoleRecorder#28]
**Describe the bug**

**Related Mapping**
AWS Config Rules
**Related Language**
Terraform
1. Go to 'aws console'
2. create AWS config.
3. Add a  new rule like s3 XX .
4. Terraform output not getting generated.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by iann0036** [comment]
Thanks for reporting!

Fix should be available in 0.3.13.
