### ISSUE TITLE
CFN AWS::CodePipeline::Pipeline mapping invalid

### ISSUE THREAD

**Issue by t04glovern** [iann0036/AWSConsoleRecorder#29]
**Describe the bug**
Whilst creating CodePipelines I've found that the CloudFormation output doesn't map the Stage properties correctly. The parameters within the Stages field are camelcase and not uppercase as per the YAML standard.

**Related Mapping**
AWS::CodePipeline::Pipeline
- Properties: Stages.Name, Stages.Actions.*

**Related Language**
CFN yml

**To Reproduce**
Create a CodePipeline, check CF YML Stages.

**Screenshots**
![screen shot 2019-02-26 at 4 05 24 pm](https://user-images.githubusercontent.com/7262516/53397072-1983be80-39e1-11e9-9c6c-0e47e7ab3f37.png)

**Comment by iann0036** [comment]
Thanks for raising Nathan!

Fix should be available in 0.3.18, available in an hour or so. If you find similar bugs, please raise as you see them. It's very appreciated.
