### ISSUE TITLE
creating a route table not working

### ISSUE THREAD

**Issue by ustrahlendorf** [iann0036/AWSConsoleRecorder#30]
**Service**
EC2

**API Calls / Actions**
create-route-table

**CloudFormation Resource Types**
AWS::EC2::RouteTable

**Additional Information**
seems that creating a route-table is not implemented, did not find it as recorded action either in CFN nor in the CLI or Boto3 output
Could also be a bug.

**Comment by iann0036** [comment]
Hi there,

Looks like that particular console area has changed slightly. The fix will be available in version 0.3.20.

Thanks for raising!

**Comment by ustrahlendorf** [comment]
Thanks Ian
