### ISSUE TITLE
Allocating a new EIP not recorded

### ISSUE THREAD

**Issue by ustrahlendorf** [iann0036/AWSConsoleRecorder#31]
**Describe the bug**
allocating a new EIP is not recorded, neither in CF, nor in CLI or Boto3; hove not checked the others.
Problem exists also when creating a new NATGW and selecting "Create New EIP" during creation process 

**Related Mapping**
missing: AWS::EC2::EIP / aws ec2 allocate-address

**Related Language**
If applicable to a specific language output, e.g. JavaScript

**To Reproduce**
Start recording
1. Go to 'VPC'
2. Click on 'Elastic IPs'
3. Click on 'Allocate new address'
4. Stop recording
5. check Recorder Dashboard; no entry under CF, only describe entries under Boto3

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by iann0036** [comment]
Thanks as always for raising!

Fixed in 0.3.21
