### ISSUE TITLE
Indent Size

### ISSUE THREAD

**Issue by alytle** [iann0036/AWSConsoleRecorder#36]
First, thanks for writing this awesome tool. It's been needed for a long time, and I really appreciate it.

For a feature request, could we consider setting a "Number of Spaces" for the Cloudformation output? Small issue, but I generally prefer 2 spaces to 4 in my CFN. 

Thanks again!

**Comment by iann0036** [comment]
Thanks for raising Andrew,

The new feature will be available in 0.3.22. Let me know if this works for you.

**Comment by alytle** [comment]
Thanks!
