### ISSUE TITLE
Option to hide ec2_client.describe_ actions

### ISSUE THREAD

**Issue by CloudCray** [iann0036/AWSConsoleRecorder#41]
**Problem**

Boto3 output comes out very noisy if performing an action through a wizard. Most of the generated python script is nothing but `ec2_client.describe_` commands.

This is especially noticeable with autocomplete form fields, such as the "add tags" form when launching an EC2 instance - a new `ec2_client.describe_tags` command is added for each keystroke.

**Requested solution**

Settings parameter or on-page filter to hide/remove all `ec2_client.describe_` actions.

Currently just doing this in a text editor, but would be a very helpful quality-of-life feature.

**Comment by iann0036** [comment]
Relates to #38.

I'll have another look at this hopefully shortly.

**Comment by CloudCray** [comment]
Looks like a subset of the issues in #38 - will close and pickup discussion there
