### ISSUE TITLE
AWS BackUp

### ISSUE THREAD

**Issue by TheOneTrueBaal** [iann0036/AWSConsoleRecorder#42]
I am trying to get a template of how to create all the required AWS Backup resources (Backup plan, backup vault, etc).

It would be of great assistance if creating the above resources using the console, while having the Console Recorder running, would create the cloudformation template for these resources, so it can be automated when recreating them.

Thanks in advance.

**Comment by iann0036** [comment]
Hi there,

I'm a little behind on the resource support for Console Recorder. https://github.com/iann0036/former2 is up to date though.

No promises on when I'll get to it in here I'm afraid.

**Comment by TheOneTrueBaal** [comment]
I was not aware of former2.  That will solve exactly my problem, so thank you very much.
