### ISSUE TITLE
AWS::ECS::TaskDefinition Encountered Unsupported Property image

### ISSUE THREAD

**Issue by mackay2k4** [iann0036/AWSConsoleRecorder#44]
**Describe the bug**
When recording a ECS TaskDefinition the property in **ContainerDefinitions** are recorded starting with a lowercase letter but need to be a uppercase first letter

**Related Mapping**
AWS::ECS::TaskDefinition

**Related Language**
Cloudfomration (maybe others as well)

**To Reproduce**
1. Record AWS::ECS::TaskDefinition 
2. check CF script
3. see **image** instead of **Image** (other as well)

**Expected behavior**
should be **Image**

**Comment by iann0036** [comment]
Hi there,

Thanks for raising!

I've gotten some fixes in release 0.3.27, which should be available roughly one hour from now. The update isn't tested fully so if there are any issues please let me know.

**Comment by mackay2k4** [comment]
seems to be working now, thanks.
