### ISSUE TITLE
Cloudformation for service catalog product - error in array names

### ISSUE THREAD

**Issue by darf53** [iann0036/AWSConsoleRecorder#45]
**Describe the bug**
When uploading a new product in service catalog, following cloudformation snippet is created:
```
    Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      Name: "EC2-instance-v1"
      Description: ""
      Owner: "owner1"
      Distributor: ""
      SupportEmail: "owner1@example.com"
      ProvisioningArtifactParameters: 
          type: "CLOUD_FORMATION_TEMPLATE"
          name: "EC2-instance-v1"
          description: ""
          info: 
            LoadTemplateFromURL: "https://s3.amazonaws.com/cf-templates-1wfdfsyejhajha-eu-west-1/servicecatalog-product-20fdsfsdfsd_catalog.yml"
```

**Related Mapping**
`AWS::ServiceCatalog::CloudFormationProduct`

**Related Language**
cloudformation

**To Reproduce**
1. Go to service catalog
2. Click on upload product
3. See error in console recorder for cloudformation

**Expected behavior**
Output for ProvisioningArtifactParameters
```
     Type: "AWS::ServiceCatalog::CloudFormationProduct"
    Properties:
      Name: "EC2-instance-v1"
      Description: ""
      Owner: "owner1"
      Distributor: ""
      SupportEmail: "owner1@example.com"
      ProvisioningArtifactParameters: 
          - 
            Name: "EC2-instance-v1"
            Description: ""
            Info: 
              LoadTemplateFromURL: "https://s3.amazonaws.com/cf-templates-1wfdfsyejhajha-eu-west-1/servicecatalog-product-20fdsfsdfsd_catalog.yml"
```

1. type seems not supported
2. capital letters needed for Name,Description,Info..... 
3. "-" to define array

**Screenshots**

**Additional context**

**Comment by iann0036** [comment]
Thanks for raising!

I've got the fix in version 0.3.28 which should be available for either Chrome or Firefox within the next hour.

If the issue is still occurring with the new version, feel free to reopen.
