### ISSUE TITLE
Identifying which HTTP requests are API calls automatically

### ISSUE THREAD

**Issue by PenelopeFudd** [iann0036/AWSConsoleRecorder#46]
**Is your feature request related to a problem? Please describe.**
I'm finding that AWS keeps changing their console, which breaks AWS Console Recorder (ACR).

**Describe the solution you'd like**
It might help if ACR detected requests that had json in the request/response body, and if it didn't have a rule for deciphering it, at least tell the user about it.

**Describe alternatives you've considered**
The current system of reporting APIs that are broken is labor-intensive and probably doesn't scale.

**Additional context**
I love this tool!  It was recommended to me by AWS Premium Support.  However, it's frustrating when the API call I need is the one that doesn't get recorded due to some small change by AWS. 

Thanks!

**Comment by iann0036** [comment]
Hi Penelope,

Thanks for your feedback. I like your idea, however the AWS Console ecosystem varies wildly in the way request/response models work.

You may be interested to know I have a companion extension which helps be write this over at https://github.com/iann0036/AWSConsoleRecorderGenerator . The generator records all actions and auto-suggests the correct mappings. This however is not always correct and needs human intervention. There is also a very significant amount of requests which are irrelevant.

Also check out https://github.com/iann0036/former2 which is much more reliable at determining the state as it performs read actions with the AWS APIs instead.
