### ISSUE TITLE
Error in CLI syntax: Tag -> Tags

### ISSUE THREAD

**Issue by PenelopeFudd** [iann0036/AWSConsoleRecorder#47]
I created an EBS volume from a snapshot, and used the AWS CLI version:
```
aws ec2 create-volume --volume-type "gp2" --size 80 --availability-zone "us-west-2a" \
 --snapshot-id "snap-00000000000007" --no-encrypted \
 --tag-specifications '[{"ResourceType":"volume", \
  "Tag":[\
    {"Key":"Name","Value":"volume-from-snapshot-of-ec2-prod-buildserv"}\
    ] \
  }]' --region us-west-2
```
This failed, because "Tag" needed to be "Tags".

Also, the other language versions show the tags except TerraForm:
```
resource "aws_ebs_volume" "ec211111111" {
    type = "gp2"
    size = 80
    availability_zone = "us-west-2a"
    snapshot_id = "snap-000000000007"
    encrypted = false
    tags {
        
    }

}
```

Version 0.3.29

Love the program!  Thanks!

**Comment by iann0036** [comment]
Thanks for raising Penelope!

I've pushed a fix in version 0.3.31, which should be available shortly. Please let me know if the fix does not work correctly.
