### ISSUE TITLE
Empty Popup when pinned to Overflow Menu in Firefox

### ISSUE THREAD

**Issue by ansgarm** [iann0036/AWSConsoleRecorder#49]
When you pin the extension to the Overflow Window in Firefox 72 (right-click > Pin to Overflow Menu) only a white empty popup is shown. Works fine when unpinned.

<img width="411" alt="Screenshot 2020-01-31 at 11 49 11" src="https://user-images.githubusercontent.com/1112056/73533901-280ffc80-4420-11ea-804f-b01c364ac62a.png">

(ACR 0.3.31 in Firefox 72.0.2 on OS X 10.14.6)

**Comment by iann0036** [comment]
Hi Ansgar,

Thanks for raising!

I've adjusted the popup page styling in 0.3.32 that should allow it to show in an overflow menu box. Note that I haven't adjusted it to be center-aligned to the full menu box as I'm not super familiar with it.

Let me know if the updated version helps.

**Comment by ansgarm** [comment]
Wow, thank you for the quick response! And the fix.  
It works like a charm – even seems to be centered. But I wouldn't care if it wasn't as long as I can press the buttons 😄  
Have a nice weekend!
