### ISSUE TITLE
Extension Records (almost) no actions

### ISSUE THREAD

**Issue by borkod** [iann0036/AWSConsoleRecorder#58]
Hello.
I recently heard about this extension and wanted to give it a try. I installed the extension on Chrome (Version 87.0.4280.66 (Official Build) (64-bit)). I clicked "Start Recording" button and tried to create few resources using AWS console (S3 bucket, SQS, DynamoDB). None of the actions produced expected output. When creating SQS or DynamoDB, no actions were recorded at all. When creating S3 bucket (with default configuration), the only actions that get recorded are to block public access:

Couple of samples:

boto3:
```
import boto3

s3control_client = boto3.client('s3control', region_name='ca-central-1')

response = s3control_client.put_public_access_block(
    PublicAccessBlockConfiguration={
        'BlockPublicAcls': True,
        'IgnorePublicAcls': True,
        'BlockPublicPolicy': True,
        'RestrictPublicBuckets': True
    }
)
```
AWS CLI:
```
aws s3control put-public-access-block --public-access-block-configuration "{\"BlockPublicAcls\":true,\"IgnorePublicAcls\":true,\"BlockPublicPolicy\":true,\"RestrictPublicBuckets\":true}" --region ca-central-1
```

The output is exactly the same regardless what region I create the S3 bucket.  If I allow public access on the S3 bucket creation screen, the above does not get produced.

I've tried creating resources in different regions with no success. I've tried the extension on couple of different laptops. I get exactly the same behavior. I've also tried turning off all other chrome extension in case that was causing some issues, but that didn't help.

Is something broken?  or am I doing something wrong?

**Comment by iann0036** [comment]
Hey @borkod,

Apologies, this isn't your fault. AWS are in the middle of changing a whole bunch of their consoles and, subsequently, this extension loses the ability to interpret the actions.

Whilst I work on improvements, you might consider the more stable [Former2](https://github.com/iann0036/former2).

**Comment by borkod** [comment]
Thanks for the confirmation.
